name: Remove an entry from the release tracking directory
description: |
  Remove an entry from the release tracking directory.

inputs:
  repository:
    description: The release tracking repository
    required: true
  path:
    description: The directory where the repository was cloned
    default: src/tracker
  storage:
    description: Subdirectory within the repository the tracking files are stored.
    default: releases
  track:
    description: The track for the release
    required: true
  version:
    description: The version for the release
    required: true
  created_at:
    description: The release timestamp. Any release matching the version will be deleted if unspecified.
  match-re:
    description: |
      Match versions using a regular expression over the string "{created_at}__{version}".
      This feature is experimental, and you may run into "quote hell".
  commit:
    description: Commit changes to the local repository. Set to empty to disable.
    default: yes
  push:
    description: Push new commit to remote repository. Set to empty to disable.
    default: yes
  entries:
    description: A new-line separated list of version id (date + version) to be deleted.

runs:
  using: "composite"
  steps:
    - name: Delete release log entry
      shell: python
      run: |
        import sys
        from pathlib import Path
        src_dir = Path("${{ github.action_path }}").parent.parent / "src"
        sys.path.insert(0, str(src_dir))

        from release_tracker import ReleaseTracker

        tracker = ReleaseTracker(
          repository="${{ inputs.repository }}",
          path="${{ inputs.path }}",
          storage="${{ inputs.storage }}")

        deleted = tracker.delete(
          track="${{ inputs.track }}",
          version="${{ inputs.version }}",
          created_at="${{ inputs.created-at }}",
          match_re="""${{ inputs.match-re }}""",
          commit=bool("${{ inputs.commit }}"),
          push=bool("${{ inputs.push }}"),
          entries="""
            ${{ inputs.entries }}
          """)
        
        # Add release log entry
        print("::group::Deleted Entries")
        print(yaml.safe_dump(deleted))
        print("::endgroup::")
