name: Remove an entry from the release tracking directory
description: |
  Remove an entry from the release tracking directory.

inputs:
  tracks-dir:
    description: The release tracking directory
    default: releases
  track:
    description: The track for the new release
    required: true
  version:
    description: A unique version id for the new release
    required: true
  created_at:
    description: A timestamp for the new releases. Any release matching the version will be deleted if unspecified.
  match-re:
    description: |
      Match versions using a regular expression over the string "{created_at}__{version}".
      This feature is experimental, and you may run into "quote hell".

runs:
  using: "composite"
  steps:
    - name: Delete release log entry
      shell: python
      run: |
        import sys
        sys.path.insert(0, "${{ github.action_path }}/src")
        from release_tracker import delete
        delete(
          tracks_dir="${{ inputs.tracks-dir }}",
          track="${{ inputs.track }}",
          version="${{ inputs.version }}",
          created_at="${{ inputs.created-at }}",
          match_re="""${{ inputs.match-re }}""")
