name: Add a new entry for a docker release
description: |
  Convenience action to clone the release tracking repository,
  and add an entry for the release of one or more Docker images.

inputs:
  repository:
    description: The release tracking repository
    required: true
  path:
    description: The directory where the repository was cloned
    default: src/tracker
  storage:
    description: Subdirectory within the repository the tracking files are stored.
    default: releases
  track:
    description: The track for the new release
    required: true
  version:
    description: A unique version id for the new release
    required: true
  created_at:
    description: A timestamp for the new releases. Automatically assigned if unspecified.
  images:
    description: A newline-separated list of images included in the release.
    required: true
  commit:
    description: Commit changes to the local repository. Set to empty to disable.
    default: yes
  push:
    description: Push new commit to remote repository. Set to empty to disable.
    default: yes

outputs:
  entry:
    description: Id of the generated entry
    value: ${{ steps.add.outputs.ENTRY }}
  created_at:
    description: The timestamp for the new entry
    value: ${{ steps.add.outputs.CREATED_AT }}

runs:
  using: "composite"
  steps:
    - name: Dump image manifest
      uses: mentalsmash/actions/docker/inspect@master
      with:
        images: ${{ inputs.images }}
        output: ${{ github.action_path }}/images.json

    - name: Add entry to release tracker
      uses: mentalsmash/actions/release-tracker/add@master
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        storage: ${{ inputs.storage }}
        track: ${{ inputs.track }}
        version: ${{ inputs.version }}
        files: |
          images.json
        commit: ${{ inputs.commit }}
        push: ${{ inputs.push }}
