name: Python-based Workflow Summary
description: |
  This action allows you to generate a summary from Python
  code. The summary function will receive the project's python-based
  configuration as argument.

inputs:
  clone-dir:
    description: Directory where to clone the repository
    required: false
    default: src/repo
  path:
    description: Local path where the configuration is located.
    required: false
    default: .pyconfig
  workflow:
    description: Workflow to summarize
    required: True
  github:
    description: The workflow's `github` context as a JSON string.
    required: false
    default: ''
  inputs:
    description: The workflow's `inputs` context as a JSON string.
    required: false
    default: ''
  output:
    description: Save generated summary to a file instead of writing it to step summary.
    required: false
    default: ''

outputs:
  settings:
    description: The loaded settings in JSON format.
    value: ${{ steps.settings.outputs.SETTINGS }}
  
runs:
  using: "composite"
  steps:
    - name: Load workflow settings
      id: settings
      shell: python
      run: |
        import json
        import os
        import sys
        from pathlib import Path

        src_dir = Path("${{ github.action_path }}").parent.parent / "src"
        sys.path.insert(0, str(src_dir))
        from pyconfig import summarize

        workflow = "${{ inputs.workflow }}".strip()
        clone_dir = Path("${{ inputs.clone-dir }}".strip())
        config_dir = clone_dir / "${{ inputs.path }}"
        github = """${{ inputs.github }}""".strip()
        if not github:
          github = """${{ toJson(github) }}""".strip()
        inputs = """${{ inputs.inputs }}""".strip()
        output = "${{ inputs.output }}".strip()

        sys.path.insert(0, str(config_dir))

        summarize(
          workflow=workflow,
          clone_dir=clone_dir,
          config_dir=config_dir,
          github=github if github else None,
          inputs=inputs if inputs else None,
          output=output if output else NOne)
