name: Python-based Workflow Summary
description: |
  This action allows you to generate a summary from Python
  code. The summary function will receive the project's python-based
  configuration as argument.

inputs:
  clone-dir:
    description: Directory where to clone the repository
    required: false
    default: src/repo
  path:
    description: Local path where the configuration is located.
    required: false
    default: .pyconfig
  workflow:
    description: Workflow to summarize
    required: True
  github:
    description: The workflow's `github` context as a JSON string.
    required: false
    default: ''
  inputs:
    description: The workflow's `inputs` context as a JSON string.
    required: false
    default: ''
outputs:
  settings:
    description: The loaded settings in JSON format.
    value: ${{ steps.settings.outputs.SETTINGS }}
  
runs:
  using: "composite"
  steps:
    - name: Load workflow settings
      id: settings
      shell: python
      run: |
        import os
        import json
        from pathlib import Path

        import sys
        repo_dir = Path("${{ github.action_path }}").parent.parent.parent
        src_dir = repo_dir / "src"
        sys.path.insert(0, str(src_dir))
        from pyconfig import summarize

        workflow = "${{ inputs.workflow }}"

        clone_dir = Path("${{ inputs.clone-dir }}")

        config_dir = clone_dir / "${{ inputs.path }}"

        github = """${{ inputs.github }}"""
        if not github:
          github = """${{ toJson(github) }}"""

        inputs = """${{ inputs.inputs }}"""

        sys.path.insert(0, str(config_dir))

        summarize(
          workflow=workflow,
          clone_dir=clone_dir,
          config_dir=config_dir,
          github=github if github else None,
          inputs=inputs if inputs else None)
