name: Initialize a directory for release tracking
description: |
  This action will initialize a directory with the files and subdirectories required
  to track releases of a project.

  The following subtree will be created under `tracks-dir`:

  ```
  <tracks-dir>/
  ├── nightly
  │   └── release-log.json
  ├── stable
  │   └── release-log.json
  └── tracks.yml
  ```

  The subdirectories are controlled by `tracks.yml` (passed via the `tracks` argument),
  which is a file defining "release tracks" for the project.

  Each "release track" directory will be initialized with an empty log file.

  The file will be populated with a new entry every time a new version is
  released to that track.

inputs:
  repository:
    description: The release tracking repository
    required: true
  path:
    description: The directory where the repository was cloned
    default: src/tracker
  storage:
    description: Subdirectory within the repository the tracking files are stored.
    default: releases
  commit:
    description: Commit changes to the local repository. Set to empty to disable.
    default: yes
  push:
    description: Push new commit to remote repository. Set to empty to disable.
    default: yes
  tracks:
    description: Release tracks configuration
  token:
    description: The authentication token to access the repository

runs:
  using: "composite"
  steps:
    - name: Initialize release tracks storage
      shell: python
      run: |
        import sys
        from pathlib import Path
        src_dir = Path("${{ github.action_path }}").parent.parent / "src"
        sys.path.insert(0, str(src_dir))

        from release_tracker import ReleaseTracker

        tracker = ReleaseTracker(
          repository="${{ inputs.repository }}",
          path="${{ inputs.path }}",
          storage="${{ inputs.storage }}")

        # tracker.initialize(
        #   tracks="""
        #     ${{ inputs.tracks }}
        #   """,
        #   commit=bool("${{ inputs.commit }}"),
        #   push=bool("${{ inputs.push }}"))

        tracker.initialize(
          tracks="""
            ${{ inputs.tracks }}
          """)
    
    - name: Commit & Push
      uses: actions-js/push@master
      with:
        github_token: ${{ inputs.token }}
        directory: ${{ inputs.path }}
