#!/usr/bin/env python3
###############################################################################
# Copyright 2020-2024 Andrea Sorbini
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
# Example usage:
###############################################################################
#
# - list workflow runs for a repository:
#
#     ci-admin select-runs -r mentalsmash/uno [-f "<filter>"]
#
# - delete workflow runs for a repository:
#
#     ci-admin delete-runs -r mentalsmash/uno [-f "<filter>"]
#
# - list workflow runs for a PR:
#
#     ci-admin pr-runs -r mentalsmash/uno -N <PR-NUMBER>
#
# - Clean up workflow runs after a PR is closed:
#
#     ci-admin pr-closed -r mentalsmash/uno -N <PR-NUMBER> [--merged]
#
# - list packages for an organization (only containers supported for now):
#
#     ci-admin select-packages -o mentalsmash [-f "<filter>"]
#
# - list versions for a package (owned by an organization):
#
#     ci-admin select-versions -o uno -o mentalsmash [-f "<filter>"]
#
# - delete versions for a package (owned by an organization):
#
#     ci-admin delete-versions -o uno -o mentalsmash [-f "<filter>"]
#
###############################################################################
# Common arguments:
###############################################################################
# --interactive: dynamically select entries (requires a tty)
#        --noop: don't actually perform changes
###############################################################################
# Common arguments must be specified before the action
# (e.g. "ci-admin --interactive select-runs ...")
###############################################################################
import sys
from pathlib import Path
repo_dir = Path(__file__).parent.parent
src_dir = repo_dir / "src"
sys.path.insert(0, str(src_dir))

from ci.admin import Admin
Admin.main()
