#!/usr/bin/env python3
import sys
from pathlib import Path
repo_dir = Path(__file__).parent.parent
src_dir = repo_dir / "src"
sys.path.insert(0, str(src_dir))

from release_tracker import ReleaseTracker
ReleaseTracker.main()
