name: Run the ci-admin script
description: |
  Run the ci-admin script

inputs:
  args:
    description: Arguments to pass to ci-admin
    required: true
  token:
    description: Authentication token.
    required: true
  image:
    description: Run command inside a docker image containing the CI administration tools.
  cwd:
    description: Local directory where to run the script.
    default: ''

runs:
  using: "composite"
  steps:
    - name: "Run ci-admin"
      shell: python
      run: |
        import sys
        from pathlib import Path
        action_dir = Path("${{ github.action_path }}")
        repo_dir = action_dir.parent.parent.parent
        src_dir = repo_dir / "src"
        sys.path.insert(0, str(src_dir))
        from ci.admin import Admin
        print("::add-mask::${{ inputs.token }}")
        print("::group::ci-admin output")
        Admin.run(
          args = """
            ${{ inputs.args }}
          """,
          image = "${{ inputs.image }}",
          cwd = "${{ inputs.cwd }}",
          token = "${{ inputs.token }}")
        print("::endgroup::")
