name: Python-based Workflow Configuration
description: |
  This action allows you to load a static configuration, enhance it
  using Python code.
  
  The configuration will exported in JSON object both as an
  output (`settings`), and as the file specified by `inputs.output`.

inputs:
  clone-dir:
    description: Directory where to clone the repository
    required: false
    default: src/repo
  path:
    description: Local path where the configuration is located.
    required: false
    default: .pyconfig
  workflow:
    description: Run a configuration function for the specified workflow.
    required: false
    default: ''
  github:
    description: The workflow's `github` context as a JSON string.
    required: false
    default: ''
  inputs:
    description: The workflow's `inputs` context as a JSON string.
    required: false
    default: ''
  output:
    description: A JSON file with the final configuration.
    required: false
    default: pyconfig.json
  summarize:
    description: Generate a step summary with the loaded configuration
    required: false
    default: ''

# outputs:
#   settings:
#     description: The loaded settings in JSON format.
#     value: ${{ steps.settings.outputs.SETTINGS }}
  
runs:
  using: "composite"
  steps:
    - name: Load workflow settings
      id: settings
      shell: python
      run: |
        import json
        import os
        import sys
        from pathlib import Path
        src_dir = Path("${{ github.action_path }}").parent.parent / "src"
        sys.path.insert(0, str(src_dir))
        from pyconfig import configuration, summarize_settings

        workflow = "${{ inputs.workflow }}"

        clone_dir = Path("${{ inputs.clone-dir }}")

        config_dir = clone_dir / "${{ inputs.path }}"

        github = """${{ inputs.github }}"""
        if not github:
          github = """${{ toJson(github) }}"""

        inputs = """${{ inputs.inputs }}"""

        sys.path.insert(0, str(config_dir))
        _, _, cfg, _ = configuration(
          clone_dir=clone_dir,
          config_dir=config_dir,
          github=github if github else None,
          inputs=inputs if inputs else None,
          workflow=workflow if workflow else None,
          as_tuple=False,
          bool_to_str=True)

        cfg_json = json.dumps(cfg, indent=2)

        with Path(os.environ["GITHUB_OUTPUT"]).open("a") as output:
          output.write("SETTINGS<<EOF\n")
          output.write(cfg_json)
          output.write("\n")
          output.write("EOF\n")

        Path("${{ inputs.output }}").write_text(cfg_json)

        if "${{ inputs.summarize }}":
          with Path(os.environ["GITHUB_STEP_SUMMARY"]).open("w") as output:
            output.write(summarize_settings(
              clone_dir=clone_dir,
              config_dir=config_dir,
              cfg=cfg,
              github=github if github else None,
              inputs=inputs if inputs else None,
              workflow=workflow if workflow else None))
